### ISSUE TITLE
Error code trying to Mint Emblem Vault

### ISSUE THREAD

**Issue by bitcoin21e8** [EmblemCompany/emblem-vault-site#1]
Hi Emblem  Team,

I set up my Emblem Vault, burnt Coval to create the vault. I sent my NFT's over, and some BTC. I can see my assets in the vault,  when I click > My Vaults > Not Minted.

My issue arises when I try to mint the Vault or view my vault on on OpenSea.
Screen images of both errors attached.

Did I set my vault up incorrectly? Do I need to have a certain amount of ETH or Coval in my linked MetaMask account to Mint the vault?

Please Help! Thank you in advance. Appreciate everything you have built so far!

David

![MetaMask error](https://user-images.githubusercontent.com/41662755/159923567-fe57c2bc-aa2d-4bde-8528-7fdbbb8075c4.jpg)
![OpenSea error](https://user-images.githubusercontent.com/41662755/159923579-42e099f6-bd3b-46aa-85ad-2d85bcdf645a.jpg)

**Comment by genecyber** [comment]
You are half way there! Click “Mint Me” and you will have a fully created vault.

**Comment by bitcoin21e8** [comment]
> 

I click "Mint Me" and nothing happens. I get a "delayed minting" message in my MetaMask extension.

Do you have to have Coval tokens in your MetaMask account to "Mint Me" ??

**Comment by bitcoin21e8** [comment]
I needed to add more ETH gas into my MetaMask account before I hit Mint Me.
