### ISSUE TITLE
I can't mint my Vault!

### ISSUE THREAD

**Issue by bitcoin21e8** [EmblemCompany/emblem-vault-site#2]
I set up my Emblem Vault, burnt Coval to create the vault. It's on Ethereum Mainnet.

I sent (x13) NFT's over, and some BTC to my vault. I can see my assets in the vault, when I click > My Vaults > Not Minted.

My issue arises when I try to mint the Vault. Nothing happens! 

Did I set my vault up incorrectly? Do I need to have a certain amount of ETH in my linked MetaMask account to Mint the vault?

Please Help! Thank you in advance.

**Comment by DONOVAN7493** [comment]
HI @bitcoin21e8 I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [Metamask Support](https://metamaskzendesk.helpsconnect.live/#)

**Comment by bitcoin21e8** [comment]
Contacted MetaMask and I don't have enough ETH gas in my account!
